### ISSUE TITLE
systemctl без sudo, как такое может быть?

### ISSUE THREAD

**Issue by Lopol2010** [backmeupplz/ci-ninja#6]
Здравствуйте бородач. Вот в примере bash скрипт управляет юнитами systemctl без sudo, но когда я попытался это воспроизвести, то мне пришлось совершать дополнительные телодвижения. А именно, я нагуглил два решения: настроить некий polkit или добавить разрешения на каждую команду в sudoers. Как же у вас оно работает без этого? Спасибо.

**Comment by backmeupplz** [comment]
Пример неверный, подразумевает запуск скрипта из-под root, надо будет поменять. Спасибо за замечание!
