### ISSUE TITLE
ref is empty

### ISSUE THREAD

**Issue by ddubovitsky** [backmeupplz/ci-ninja#8]
Hi there! Whatever I get hook I see that ref is empty. 
I reverted https://github.com/backmeupplz/ci-ninja/commit/b3a5df87819d22002c19084cc24d704931f2c9ca#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346 
change back and everything got back to working again.

**Comment by backmeupplz** [comment]
Lol, I knew that would break something, should be fixed now, thank you for catching this!
